namespace Mutty.Generator.CodeHelpers;

public class IndentedCodeBuilder
{
    private readonly IndentedStringBuilder _stringBuilder = new(0, 4);

    public void Line(string line) 
        => _stringBuilder.AppendLine(line);

    public void EmptyLine()
        => _stringBuilder.AppendLine(string.Empty);
    
    public void Comment(string comment)
        => _stringBuilder.AppendLine($"// {comment}");
    
    public void CommentAutoGenerated()
    {
        Comment("<auto-generated />");
        Comment("This file is auto-generated by Mutty.");
        EmptyLine();
    }

    public IDisposable Indent()
        => _stringBuilder.Indent();
    
    public void Braces(Action action, string suffix = "")
    {
        _stringBuilder.AppendLine("{");
        using (Indent())
        {
            action();
        }
        _stringBuilder.AppendLine("}" + suffix);
    }

    public override string ToString()
        => _stringBuilder.ToString();
}