// Copyright (c) 2020-2024 Atypical Consulting SRL. All rights reserved.
// Atypical Consulting SRL licenses this file to you under the Apache 2.0 license.
// See the LICENSE file in the project root for full license information.

using Mutty.CodeHelpers;
using NUnit.Framework;
using Shouldly;

namespace Mutty.Tests;

[TestFixture]
public class IndentedCodeBuilderTests
{
    [Test]
    public void Constructor_CreatesEmptyBuilder()
    {
        IndentedCodeBuilder builder = new();

        builder.ToString().ShouldBe(string.Empty);
    }

    [Test]
    public void Line_AppendsLineWithNewLine()
    {
        IndentedCodeBuilder builder = new();
        builder.Line("public class Test");

        builder.ToString().ShouldBe($"public class Test{Environment.NewLine}");
    }

    [Test]
    public void EmptyLine_AppendsEmptyLine()
    {
        IndentedCodeBuilder builder = new();
        builder.Line("First");
        builder.EmptyLine();
        builder.Line("Second");

        builder.ToString().ShouldBe($"First{Environment.NewLine}{Environment.NewLine}Second{Environment.NewLine}");
    }

    [Test]
    public void Comment_AppendsCommentWithSlashes()
    {
        IndentedCodeBuilder builder = new();
        builder.Comment("This is a comment");

        builder.ToString().ShouldBe($"// This is a comment{Environment.NewLine}");
    }

    [Test]
    public void CommentAutoGenerated_AppendsStandardHeader()
    {
        IndentedCodeBuilder builder = new();
        builder.CommentAutoGenerated();

        string expected = $"// <auto-generated />{Environment.NewLine}"
            + $"// This file is auto-generated by Mutty.{Environment.NewLine}"
            + $"{Environment.NewLine}";

        builder.ToString().ShouldBe(expected);
    }

    [Test]
    public void Indent_WithAction_IndentsContent()
    {
        IndentedCodeBuilder builder = new();
        builder.Line("namespace Test");
        builder.Indent(() => { builder.Line("public class MyClass"); });

        string expected = $"namespace Test{Environment.NewLine}"
            + $"    public class MyClass{Environment.NewLine}";

        builder.ToString().ShouldBe(expected);
    }

    [Test]
    public void Indent_WithUsing_IndentsContent()
    {
        IndentedCodeBuilder builder = new();
        builder.Line("namespace Test");

        using (builder.Indent())
        {
            builder.Line("public class MyClass");
        }

        builder.Line("// Outside indent");

        string expected = $"namespace Test{Environment.NewLine}"
            + $"    public class MyClass{Environment.NewLine}"
            + $"// Outside indent{Environment.NewLine}";

        builder.ToString().ShouldBe(expected);
    }

    [Test]
    public void Braces_GeneratesCodeBlock()
    {
        IndentedCodeBuilder builder = new();
        builder.Line("public class Test");
        builder.Braces(() => { builder.Line("private int _field;"); });

        const string expected =
            """
            public class Test
            {
                private int _field;
            }

            """;

        builder.ToString().ShouldBe(expected);
    }

    [Test]
    public void Braces_WithSuffix_AppendsSuffixAfterClosingBrace()
    {
        IndentedCodeBuilder builder = new();
        builder.Line("return new Test");
        builder.Braces(
            () => builder.Line("Property = value"),
            ";");

        const string expected =
            """
            return new Test
            {
                Property = value
            };

            """;

        builder.ToString().ShouldBe(expected);
    }

    [Test]
    public void Summary_GeneratesXmlDocumentation()
    {
        IndentedCodeBuilder builder = new();
        builder.Summary("This is a test class.");

        string expected = $"/// <summary>{Environment.NewLine}"
            + $"/// This is a test class.{Environment.NewLine}"
            + $"/// </summary>{Environment.NewLine}";

        builder.ToString().ShouldBe(expected);
    }

    [Test]
    public void SummaryParam_GeneratesParameterDocumentation()
    {
        IndentedCodeBuilder builder = new();
        builder.SummaryParam("value", "The value to process.");

        string expected = $"/// <param name=\"value\">The value to process.</param>{Environment.NewLine}";

        builder.ToString().ShouldBe(expected);
    }

    [Test]
    public void NestedBraces_GeneratesNestedBlocks()
    {
        IndentedCodeBuilder builder = new();
        builder.Line("namespace Test");
        builder.Braces(() =>
        {
            builder.Line("public class MyClass");
            builder.Braces(() =>
            {
                builder.Line("public void Method()");
                builder.Braces(() => { builder.Line("Console.WriteLine(\"Hello\");"); });
            });
        });

        const string expected =
            """
            namespace Test
            {
                public class MyClass
                {
                    public void Method()
                    {
                        Console.WriteLine("Hello");
                    }
                }
            }

            """;

        builder.ToString().ShouldBe(expected);
    }

    [Test]
    public void CompleteClassGeneration_ProducesCorrectOutput()
    {
        IndentedCodeBuilder builder = new();

        builder.CommentAutoGenerated();
        builder.Line("using System;");
        builder.EmptyLine();
        builder.Line("namespace MyNamespace");
        builder.Braces(() =>
        {
            builder.Summary("Represents a person.");
            builder.Line("public class Person");
            builder.Braces(() =>
            {
                builder.Line("private string _name;");
                builder.EmptyLine();

                builder.Summary("Initializes a new instance of the Person class.");
                builder.SummaryParam("name", "The person's name.");
                builder.Line("public Person(string name)");
                builder.Braces(() => { builder.Line("_name = name;"); });
                builder.EmptyLine();

                builder.Summary("Gets the person's name.");
                builder.Line("public string Name => _name;");
            });
        });

        const string expected =
            """
            // <auto-generated />
            // This file is auto-generated by Mutty.

            using System;

            namespace MyNamespace
            {
                /// <summary>
                /// Represents a person.
                /// </summary>
                public class Person
                {
                    private string _name;

                    /// <summary>
                    /// Initializes a new instance of the Person class.
                    /// </summary>
                    /// <param name="name">The person's name.</param>
                    public Person(string name)
                    {
                        _name = name;
                    }

                    /// <summary>
                    /// Gets the person's name.
                    /// </summary>
                    public string Name => _name;
                }
            }

            """;

        builder.ToString().ShouldBe(expected);
    }

    [Test]
    public void MixedIndentationMethods_WorkTogether()
    {
        IndentedCodeBuilder builder = new();

        builder.Line("public void Method()");
        builder.Line("{");

        // Mix using statement and action-based indentation
        using (builder.Indent())
        {
            builder.Comment("First level");
            builder.Indent(() => { builder.Comment("Second level"); });
            builder.Comment("Back to first level");
        }

        builder.Line("}");

        const string expected =
            """
            public void Method()
            {
                // First level
                    // Second level
                // Back to first level
            }

            """;

        builder.ToString().ShouldBe(expected);
    }

    [Test]
    public void EmptyBraces_GeneratesCorrectly()
    {
        IndentedCodeBuilder builder = new();
        builder.Line("public void EmptyMethod()");
        builder.Braces(() => { });

        const string expected =
            """
            public void EmptyMethod()
            {
            }

            """;

        builder.ToString().ShouldBe(expected);
    }

    [Test]
    public void CommentsWithIndentation_IndentCorrectly()
    {
        IndentedCodeBuilder builder = new();
        builder.Line("public class Test");
        builder.Braces(() =>
        {
            builder.Comment("This is an indented comment");
            builder.Line("private int _field;");
        });

        const string expected =
            """
            public class Test
            {
                // This is an indented comment
                private int _field;
            }

            """;

        builder.ToString().ShouldBe(expected);
    }

    [Test]
    public void MultipleSummaryParams_GenerateCorrectly()
    {
        IndentedCodeBuilder builder = new();
        builder.Summary("Adds two numbers.");
        builder.SummaryParam("a", "The first number.");
        builder.SummaryParam("b", "The second number.");
        builder.Line("public int Add(int a, int b) => a + b;");

        string expected = $"/// <summary>{Environment.NewLine}"
            + $"/// Adds two numbers.{Environment.NewLine}"
            + $"/// </summary>{Environment.NewLine}"
            + $"/// <param name=\"a\">The first number.</param>{Environment.NewLine}"
            + $"/// <param name=\"b\">The second number.</param>{Environment.NewLine}"
            + $"public int Add(int a, int b) => a + b;{Environment.NewLine}";

        builder.ToString().ShouldBe(expected);
    }

    [Test]
    public void IndentSize_UsesFourSpaces()
    {
        IndentedCodeBuilder builder = new();
        builder.Indent(() => { builder.Line("Indented"); });

        // Verify it uses 4 spaces (as set in the constructor)
        builder.ToString().ShouldStartWith("    Indented");
    }
}
