// Copyright (c) 2020-2024 Atypical Consulting SRL. All rights reserved.
// Atypical Consulting SRL licenses this file to you under the Apache 2.0 license.
// See the LICENSE file in the project root for full license information.

using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using NUnit.Framework;
using Shouldly;

namespace Mutty.Tests;

public class MutableRecordGeneratorTests
{
    [SetUp]
    public void Setup()
    {
    }

    [Test]
    public void ShouldGenerateMutableRecord()
    {
        // Arrange
        string input = GetInput();
        string outputAttribute = GetOutputAttribute();
        string outputMutable = GetOutputMutable();
        string outputExtensions = GetOutputExtensions();

        // Act
        string[] generatedOutputs = GetGeneratedOutput(input);
        string resultAttribute = generatedOutputs.First(x => x.Contains("class MutableGenerationAttribute"));
        string resultMutable = generatedOutputs.First(x => x.Contains("class MutableStudentDetails"));
        string resultExtensions = generatedOutputs.First(x => x.Contains("class StudentDetailsExtensions"));

        // Assert
        resultAttribute.ShouldBe(outputAttribute);
        resultMutable.ShouldBe(outputMutable);
        resultExtensions.ShouldBe(outputExtensions);
    }

    private static string[] GetGeneratedOutput(string sourceCode)
    {
        SyntaxTree syntaxTree = CSharpSyntaxTree.ParseText(sourceCode);
        IEnumerable<MetadataReference> references = AppDomain.CurrentDomain.GetAssemblies()
            .Where(static assembly => !assembly.IsDynamic && !string.IsNullOrWhiteSpace(assembly.Location))
            .Select(static assembly => MetadataReference.CreateFromFile(assembly.Location))
            .Cast<MetadataReference>()
            .Concat([MetadataReference.CreateFromFile(typeof(MutableGenerationAttribute).Assembly.Location)]);

        CSharpCompilation compilation = CSharpCompilation.Create(
            "SourceGeneratorTests",
            [syntaxTree],
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        // Single source generator under test
        MuttyGenerator generator = new();

        _ = CSharpGeneratorDriver.Create(generator)
            .RunGeneratorsAndUpdateCompilation(
                compilation,
                out Compilation outputCompilation,
                out ImmutableArray<Diagnostic> diagnostics);

        // optional
        diagnostics.Where(static d => d.Severity == DiagnosticSeverity.Error).ShouldBeEmpty();

        string[] generatedOutput = outputCompilation
            .SyntaxTrees
            .Skip(1)
            .Select(static tree => tree.ToString())
            .ToArray();

        return generatedOutput;
    }

    private static string GetInput()
    {
        return
            """
            using System.Collections.Immutable;
            using Mutty;
            using Mutty.Tests.Setup;

            namespace Mutty.Tests;

            [MutableGeneration]
            public record StudentDetails(string Name, int Age);
            """;
    }

    private static string GetOutputAttribute()
    {
        return
            """
            // <auto-generated />
            // This file is auto-generated by Mutty.

            using System;

            namespace Mutty
            {
                /// <summary>
                /// Indicates that the class is mutable and can be generated by the Mutty generator.
                /// </summary>
                [AttributeUsage(AttributeTargets.Class, Inherited = false)]
                public class MutableGenerationAttribute : Attribute
                {
                    /// <summary>
                    /// Initializes a new instance of the <see cref="MutableGenerationAttribute" /> class.
                    /// </summary>
                    public MutableGenerationAttribute() { }
                }
            }

            """;
    }

    private static string GetOutputMutable()
    {
        return
            """
            // <auto-generated />
            // This file is auto-generated by Mutty.

            #nullable enable

            using System.Collections.Generic;
            using System.Collections.Immutable;
            using System.Linq;

            namespace Mutty.Tests
            {
                /// <summary>
                /// The mutable wrapper for the <see cref="StudentDetails"/> record.
                /// </summary>
                public partial class MutableStudentDetails
                {
                    private StudentDetails _record;

                    /// <summary>
                    /// Initializes a new instance of the <see cref="MutableStudentDetails"/> class.
                    /// </summary>
                    /// <param name="record">The record to wrap.</param>
                    public MutableStudentDetails(StudentDetails record)
                    {
                        _record = record;

                        Name = _record.Name;
                        Age = _record.Age;
                    }

                    /// <summary>
                    /// Builds a new instance of the <see cref="StudentDetails"/> class.
                    /// </summary>
                    public StudentDetails Build()
                    {
                        OnBeforeBuild();
                        return _record with
                        {
                            Name = this.Name,
                            Age = this.Age,
                        };
                    }

                    /// <summary>
                    /// Builds a new instance of the <see cref="StudentDetails"/> record. Alias for <see cref="Build"/>.
                    /// </summary>
                    public StudentDetails ToImmutable()
                    {
                        return Build();
                    }

                    /// <summary>
                    /// Called at the start of <see cref="Build"/>, before the immutable record is produced.
                    /// </summary>
                    /// Implement this method in a user-defined partial class to validate or normalise state.
                    partial void OnBeforeBuild();

                    /// <summary>
                    /// Performs an implicit conversion from <see cref="StudentDetails"/> to <see cref="MutableStudentDetails"/>.
                    /// </summary>
                    public static implicit operator MutableStudentDetails(StudentDetails record)
                    {
                        return new MutableStudentDetails(record);
                    }

                    /// <summary>
                    /// Performs an explicit conversion from <see cref="MutableStudentDetails"/> to <see cref="StudentDetails"/>.
                    /// </summary>
                    /// <remarks>Explicit because it allocates a new record; prefer <see cref="Build"/>.</remarks>
                    public static explicit operator StudentDetails(MutableStudentDetails mutable)
                    {
                        return mutable.Build();
                    }

                    /// <summary>
                    /// Gets or sets the Name.
                    /// </summary>
                    public string Name { get; set; }

                    /// <summary>
                    /// Gets or sets the Age.
                    /// </summary>
                    public int Age { get; set; }
                }
            }

            """;
    }

    private static string GetOutputExtensions()
    {
        return
            """
            // <auto-generated />
            // This file is auto-generated by Mutty.

            using System;
            using System.Collections.Generic;
            using System.Collections.Immutable;
            using System.Linq;

            namespace Mutty.Tests
            {
                /// <summary>
                /// The mutable extensions for the <see cref="StudentDetails"/> record.
                /// </summary>
                public static class StudentDetailsExtensions
                {
                    /// <summary>
                    /// Produces a new instance of the <see cref="StudentDetails"/> record.
                    /// </summary>
                    public static StudentDetails Produce(this StudentDetails baseState, Action<MutableStudentDetails> recipe)
                    {
                        var draftState = new MutableStudentDetails(baseState);
                        recipe(draftState);
                        var resultState = draftState.Build();
                        return resultState;
                    }

                    /// <summary>
                    /// Creates a new instance of the <see cref="MutableStudentDetails"/> record.
                    /// </summary>
                    public static MutableStudentDetails CreateDraft(this StudentDetails baseState)
                    {
                        return new MutableStudentDetails(baseState);
                    }

                    /// <summary>
                    /// Finishes the draft and builds a new instance of the <see cref="StudentDetails"/> record.
                    /// </summary>
                    public static StudentDetails FinishDraft(this MutableStudentDetails draft)
                    {
                        return draft.Build();
                    }

                    /// <summary>
                    /// Converts a collection of <see cref="StudentDetails"/> records to mutable.
                    /// </summary>
                    public static List<MutableStudentDetails> AsMutable(this IEnumerable<StudentDetails> baseStates)
                    {
                        return baseStates.Select(e => new MutableStudentDetails(e)).ToList();
                    }

                    /// <summary>
                    /// Converts a collection of <see cref="MutableStudentDetails"/> records to immutable.
                    /// </summary>
                    public static ImmutableList<StudentDetails> ToImmutable(this IEnumerable<MutableStudentDetails> mutableStates)
                    {
                        return mutableStates.Select(x => x.Build()).ToImmutableList();
                    }
                }
            }

            """;
    }
}
